Add fork-ts-checker-webpack-plugin resolution
Squashes warning from:
node_modules/react-dev-utils/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/profile/TypeScriptPerformance.js:12:36)

TypeError: Cannot set property mark of #<Object> which has only a getter